### ISSUE TITLE
Failed to parse JSON file  src/.../.DS_Store

### ISSUE THREAD

**Issue by gfarb** [pozil/postman-extractor#3]
On Mac OS, after importing the JSON data dump and removing any unneeded files (the JSON dump file, other collections, other environments...), because/if the 'src' directory and any sub-directories are opened, .DS_Store files are created.

When these hidden .DS_Store files are created the pmx export command beings to fail and throws the following error message:
```
Failed to parse JSON file src/.../.DS_Store
    SyntaxError: Unexpected token  in JSON at position 0
```

To tentatively resolve the issue, I would run the following command in each sub-directory a .DS_Store file was created in: 
`find . -name '.DS_Store' -type f -delete`

**Comment by pozil** [comment]
Thanks for reporting this issue @mhgoldfarb.
I've just released a new version (1.1.0) that safely ignores those system files.
